### ISSUE TITLE
Error when I click on a contact

### ISSUE THREAD

**Issue by Jeronimo17** [hoehermann/wxpyWha#11]
Hi, thanks for the gui

I have an error when I click on a contact, and the chat window does not open

Would you know how to fix this? I am on windows xp

```
Phonebook loaded from CSV has 1 entries.
C:\wxpyWha-master\gui\_generated.py:72: wxPyDeprecationWarning: Call to deprecat
ed item. Use SetSizeHints instead.
  self.SetSizeHintsSz( wx.DefaultSize, wx.DefaultSize )
IOError: History was not loaded.
Loaded 0 messages.
Success: Logged in.
C:\wxpyWha-master\gui\_generated.py:22: wxPyDeprecationWarning: Call to deprecat
ed item. Use SetSizeHints instead.
  self.SetSizeHintsSz( wx.DefaultSize, wx.DefaultSize )
Traceback (most recent call last):
  File "C:\wxpyWha-master\gui\ConversationListFrame.py", line 108, in onListBox
    self.conversationFrame(jid)
  File "C:\wxpyWha-master\gui\ConversationListFrame.py", line 94, in conversatio
nFrame
    cf = ConversationFrame(self, self.client, jid, self.phonebook.jid_to_name(ji
d))
  File "C:\wxpyWha-master\gui\ConversationFrame.py", line 48, in __init__
    _generated.ConversationFrame.__init__(self, parent)
  File "C:\wxpyWha-master\gui\_generated.py", line 43, in __init__
    self.StatusBar1 = self.CreateStatusBar( 1, wx.ST_SIZEGRIP, wx.ID_ANY )
AttributeError: 'module' object has no attribute 'ST_SIZEGRIP'
```

**Comment by Jeronimo17** [comment]
I have changed these things:

wxpyWha-master\gui\_generated.py

line 22 and line 72: self.SetSizeHintsSz( wx.DefaultSize, wx.DefaultSize ) to self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )

line 43: self.StatusBar1 = self.CreateStatusBar( 1, wx.ST_SIZEGRIP, wx.ID_ANY ) to self.StatusBar1 = self.CreateStatusBar( 1 )

And now does not fail until a message is sent:

![test1](https://user-images.githubusercontent.com/4985763/27396713-3bdb55cc-56b4-11e7-819b-cdbc359f9ca8.png)
![test2](https://user-images.githubusercontent.com/4985763/27396715-3e37a17c-56b4-11e7-8ef7-28a78ef0917b.png)
Infinite waiting for response from server

yowsup-cli it works

```
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.demos.sendclient.layer:Message sent

Yowsdown
```

**Comment by Jeronimo17** [comment]
I already answered myself, the problem was that I was not putting the format 34xxxxxxxxx@s.whatsapp.net hehe.

Thank you works well, it would be nice to add more functions than yowsup has. :)

**Comment by hoehermann** [comment]
Thank you for sorting this out yourself.
Unfortunately, the future of this application is not too bright. See #17.
