### ISSUE TITLE
Error in Windows with "ConversationFrame.py"

### ISSUE THREAD

**Issue by Jeronimo17** [hoehermann/wxpyWha#12]
The previous version has no problems

```
Traceback (most recent call last):
  File "C:\wxpyWha-master\gui\ConversationListFrame.py", line 107, in onListBox
    self.conversationFrame(jid)
  File "C:\wxpyWha-master\gui\ConversationListFrame.py", line 96, in conversatio
nFrame
    cf.append(message, new and idx == len(self.conversations[jid])-1) # mark onl
y last message as new
  File "C:\wxpyWha-master\gui\ConversationFrame.py", line 142, in append
    line
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 26: ordinal
 not in range(128)
```

**Comment by Jeronimo17** [comment]
I found a solution

At the beginning of the file ConversationFrame.py
```
import sys  

reload(sys)  
sys.setdefaultencoding('utf8')
```

**Comment by hoehermann** [comment]
Thank you for the report and the solution you are offering. Nontheless I want to understand the problem. I assume by "previous version has no problems" you mean " 62f6b80 is fine, but b06d13a is not ". Please tell me

* yowsup backend (fork and commit)
* Python version
* Operating system

**Comment by Jeronimo17** [comment]
Sorry, I was referring to the previous one that I had, which should be 

- yowsup      v2.5.7
- ConversationFrame.py "22 Mar 2017 1 parent 66a1188 commit 33b9a3454f1dce6d5e27dacea3b472f688b3adb7 "
- Python 2.7
- Windows XP 32
[ConversationFrame.zip](https://github.com/hoehermann/wxpyWha/files/1769274/ConversationFrame.zip)

**Comment by hoehermann** [comment]
Okay. Thank you. I only test using Python 3 and yowsup version 2.5.2 (AragurDEV's fork). Encoding is handled differently in that constellation. Good to know that yowsup version 2.5.7 by tgalal works with Python 2.

**Comment by hoehermann** [comment]
On my system, yowsup v2.5.7 from tgalal fails to connect. I cannot reproduce the issue nor test the changes. Might be tied to the operating system. Please understand that I will not reinstall Windows XP these days. So I just hope 99a0b84 works for you.

**Comment by Jeronimo17** [comment]
The latest changes work perfectly, thank you very much Hoehermann

How strange it does not connect you yowsup v2.5.7 
Can it be something from here? yowsup/env/env_s40.py
