### ISSUE TITLE
Blinking window

### ISSUE THREAD

**Issue by Jeronimo17** [hoehermann/wxpyWha#13]
Is there any way to make the Windows window flash at least by changing this?
In ConversationListFrame.py
`cf.Raise() # bring to front`

Can you put it on cf. something to flash instead of bring to front?
I have put it as a comment, so that I can do something else while receiving messages

**Comment by hoehermann** [comment]
Does `cf.RequestUserAttention()` work better for you?

**Comment by Jeronimo17** [comment]
Put, tomorrow when they talk, I'll tell you

**Comment by Jeronimo17** [comment]
It works perfect, thank you very much :)
