### ISSUE TITLE
Avoid window flash when sending text

### ISSUE THREAD

**Issue by Jeronimo17** [hoehermann/wxpyWha#15]
Avoid window flash when sending text, and just flash once when it connects and many messages are received

```
def conversationFrame(self, jid, message = None, new = False):
        # Setting new to default True will always re-process last media-message
        if jid in self.conversationFrames: # frame exists
            cf = self.conversationFrames[jid] # get frame reference
            if message:
                cf.append(message, new) # append message
            # cf.Raise() # bring to front
            cf.RequestUserAttention() # flash window
        else: # frame does not exist
            # create frame
            cf = ConversationFrame(self, self.client, jid, self.phonebook.jid_to_name(jid))
            self.conversationFrames[jid] = cf # save frame reference
            for idx, message in enumerate(self.conversations[jid]): # append all messages
                cf.append(message, new and idx == len(self.conversations[jid])-1) # mark only last message as new
            cf.Show() # show frame
```

Thank you, the rest is great the rest goes great with https://github.com/AragurDEV/yowsup (in windows XP and Python 3.4.4)

**Comment by hoehermann** [comment]
Glad to hear it works for you. Unfortunately, yowsup stopped working for me (all my numbers were blocked and I cannot re-register any of them). Therefore, I cannot try my changes. Does the change with 10bb241 work for you?

**Comment by Jeronimo17** [comment]
No, with that change it's still the same

**Comment by hoehermann** [comment]
Looks I used the wrong object for querying activity state. How about now in 0ebbc90?

**Comment by Jeronimo17** [comment]
Now never flash

**Comment by hoehermann** [comment]
Dang. You are right. Now it only flashes if there is no window selected at all. I did not catch this as I have only tested with one debug conversation. I might try something else, but not today.

**Comment by hoehermann** [comment]
Gave it another shot today with 9827219.

**Comment by hoehermann** [comment]
Closed because of inactivity.
