### ISSUE TITLE
How to send a message to a contact who is not yet on the list?

### ISSUE THREAD

**Issue by hoehermann** [hoehermann/wxpyWha#4]
Question as asked by @sowerkoku.

**Answer:** Right now, you don't. Replying to incoming messages is sufficient for me. I'll keep this as an enhancement for later.

It will probably be done with an additional TextControl and Button in the ConversationListFrame. OnButtonClick locally generates a fake message originating from the entered number. This message is handled by the existing code.

**Comment by sowerkoku** [comment]
it's just what I thought, but I try to add the alias creating a false onIncomingMessage.

**Comment by hoehermann** [comment]
Automatically adding the contact to the list of aliases is a good idea. But I don't want to write the aliases right now. How about the other way around? Adding contacts to the list of aliases now produces entries in the contact list upon program start.

**Comment by sowerkoku** [comment]
beautiful. lets try it and you commented.

**Comment by hoehermann** [comment]
Works for me and no negative feedback for a week. Closing.
